spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

app.seed.enabled=${APP_SEED_ENABLED}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD}
app.seed.admin.full-name=${APP_SEED_ADMIN_FULL_NAME}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true

vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.secret-key=${VNPAY_SECRET_KEY}
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${BACKEND_URL}/api/payments/vnpay-return

momo.partner-code=${MOMO_PARTNER_CODE}
momo.access-key=${MOMO_ACCESS_KEY}
momo.secret-key=${MOMO_SECRET_KEY}
momo.api-url=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect-url=${BACKEND_URL}/api/payments/momo-return
momo.ipn-url=${BACKEND_URL}/api/payments/momo-ipn

google.client.id=${GOOGLE_CLIENT_ID}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=

app.frontend.url=${FRONTEND_URL}